version: '3.8'

services:
  app:
    image: registry.gitlab.aisoftech.vn/dungdq/ai-livecode-check:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8091:8091"
    # Lệnh chạy production tối ưu: 4 workers, không reload
    command: [ "python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8091", "--workers", "4" ]
